### ISSUE TITLE
Issue(?) with the sample

### ISSUE THREAD

**Issue by sabiou** [jamowei/fritz2-ktor-todomvc#3]
I'm following the provided sample and run into this issue(?)

......
`val name = inspector.sub(L.Person.name)`

What does the `L` stand for ? Can't get it

Sincerly

**Comment by jwstegemann** [comment]
`L` is the name for the generated Object that contains all `Lenses` for a package. See the [Lenses](https://docs.fritz2.dev/Lenses.html) section in the docs for more details. (And feel free to ask if something remains unclear 😉). To get it generated you have to start the build task from gradle.

**Comment by jamowei** [comment]
Sometimes it can happen that your IDE can't see the generated `L` object which is settled under your `build` folder. Gradle overall has no problem to find that files and compiles the project fine. I opened an [issue](https://github.com/jwstegemann/fritz2/issues/234) at our fritz2 project to investigate this issue. For this reason I close this one here.
